[PEER-1047] Notifications for Sui blockchain
peeranha/peeranha-query-index pull request #2
Opened 2023-05-18 14:50 UTC by IgorAlexeew

PR for [PEER-1047](https://peer.youtrack.cloud/issue/PEER-1047)

2023-05-18 20:08 UTC, sergeyi23 approved these changes
Looks good.

2023-05-30 07:32 UTC, andreilarin requested changes

2023-05-30 07:32 UTC, andreilarin commented on src/core/sui-blockchain/sui.ts
> +  const endpoint = process.env.SUI_RPC_ENDPOINT;
do the same with all calls `getSecretValue` in this file

2023-05-30 08:46 UTC, andreilarin approved these changes

2023-06-08 07:16 UTC, sergeyi23 commented on src/core/sui-blockchain/sui.ts
> +  const endpoint = process.env.SUI_RPC_ENDPOINT;
Rollback to secret value

2023-06-08 07:17 UTC, sergeyi23 commented on src/core/sui-blockchain/sui.ts
> +  const endpoint = process.env.SUI_RPC_ENDPOINT;
Rollback to getSecretValue

2023-06-08 07:17 UTC, sergeyi23 commented on src/core/sui-blockchain/sui.ts
> +  const endpoint = process.env.SUI_RPC_ENDPOINT;
rollback to getSecretValue

2023-06-08 07:17 UTC, sergeyi23 commented on stages/dev2.yml
> +  SUI_PACKAGE_ADDRESS: '0x537ae9bb80ec56b152271a7a183a7f5e6cb3db0fff7c6221f2f7f25c8cf0e0ca'
Duplicate config values

2023-06-08 07:18 UTC, sergeyi23 commented on stages/dev3.yml
> +  SUI_PACKAGE_ADDRESS: '0x83f909002b471f7e1dbec27c837ff143189f51dff9faf42697542df82113b2ec'
Duplicate config values

2023-06-08 07:18 UTC, sergeyi23 approved these changes
Fix comments before merge

2023-06-08 08:32 UTC, merged